### ISSUE TITLE
Error in eslintrc config file

### ISSUE THREAD

**Issue by simofacc** [turrisjs/turris-gulp-tasks#6]
Hi,

I just installed turris component generator and when I try npm start I get an error because in the eslintrc config file there is a duplicate key

Error: duplicated mapping key at line 125, column 35:
        "max-nested-callbacks": [2, 1],

And in fact this key value pair is already set on line 97.

"max-nested-callbacks": [2, 3],

**Comment by yamalight** [comment]
hey, this package is no longer maintained and is not related to eslint in component generator, so I'll close this issue.

w.r.t. issue - seems like you are using newer version of eslint. you either need to use older one (I believe turris was made with 1.x in mind), or you can edit eslintrc to work with new one.

**Comment by simofacc** [comment]
Ok.

Would you suggest that I use something else than turris component generator?

I liked the idea of having component modules with scoped styles, and I wanted to try it out for my current application.

**Comment by yamalight** [comment]
if you are just looking for scoped styles, I'd suggest having a look at [css-modules](https://github.com/css-modules/css-modules) and [using them with webpack](https://github.com/css-modules/webpack-demo)
